### ISSUE TITLE
Erro: Invalid chrome version. fbSim supports Chrome 73 or higher.

### ISSUE THREAD

**Issue by mauro-cb** [morenomancosu/fbSim#4]
Hi! i'm with a problem. I was trying to use your tool and when i called "chrome_ver = 80" in "fbSetAccount" function i had "Erro: Invalid chrome version. fbSim supports Chrome 73 or higher." but, how i put in function, my version is 80 (80.0.3987.132 more specifically). There is any incompatibility with this version?

**Comment by morenomancosu** [comment]
Dear @mauro-cb , thanks for the feedback! There was actually a bug in the code. I just fixed the issue, try to re-install the package and let me know if everything is fine.
Best,
Moreno
